language: scala

scala:
  - 2.11.8

script: sbt ++$TRAVIS_SCALA_VERSION test

before_deploy:
  - mkdir -p $HOME/.bintray
  - openssl aes-256-cbc -K $encrypted_ba8b6e0b5d99_key -iv $encrypted_ba8b6e0b5d99_iv -in .credentials.enc -out $HOME/.bintray/.credentials -d

deploy:
  provider: script
  script: sbt ++$TRAVIS_SCALA_VERSION publish
  on:
    branch: master

jdk:
  - oraclejdk8
